name: Deploy GitHub Pages (main/root)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # Optional: Build step (uncomment if using a static site generator)
    # - name: Build site
    #   run: |
    #     npm install
    #     npm run build

    - name: Commit any generated files
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add .
        git commit -m "Update site [skip ci]" || echo "No changes to commit"
        git push
